name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.8.4
homepage: https://github.com/fluttercommunity/chewie

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  provider: ^6.1.2
  video_player :
  git:
    url: https://gitee.com/openharmony-sig/flutter_packages.git
    path: packages/video_player/video_player
  wakelock_plus: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
